
{ config, pkgs, ... }:

let credentials = import ./credentials.nix;
in {
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix

      ./cachix.nix

      ./display-manager.nix
      ./networking.nix
      ./sway-extra.nix
      ./shell.nix
      ./users.nix
      ./adb.nix
      ./virtualbox.nix
      ./libvirtd.nix
      ./zerotier.nix
      ./eid.nix
    ];

  boot.kernelPackages = pkgs.linuxPackages_5_6;

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  hardware.cpu.amd.updateMicrocode = true;
 
  boot.supportedFilesystems = [ "zfs" ];
  boot.zfs.requestEncryptionCredentials = true;
  boot.initrd.availableKernelModules = [ "igb" "ehci_pci" "xhci_pci" "ahci" "hid_microsoft" "hid_generic" "hid_logitech" "atkbd" ];
  services.zfs.autoScrub.enable = true;
  services.zfs.autoSnapshot.enable = true;
  services.zfs.autoReplication = {
    enable = true;
    recursive = true;
    followDelete = false;
    localFilesystem = "rpool/secure/home";
  } // credentials.zfs.replication;

  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 30d";
  };

  boot.initrd.network = {
# This will use udhcp to get an ip address.
# Make sure you have added the kernel module for your network driver to `boot.initrd.availableKernelModules`, 
# so your initrd can load it!
# Static ip addresses might be configured using the ip argument in kernel command line:
# https://www.kernel.org/doc/Documentation/filesystems/nfs/nfsroot.txt
	  enable = false;
	  ssh = {
		  enable = true;
# To prevent ssh from freaking out because a different host key is used,
# a different port for dropbear is useful (assuming the same host has also a normal sshd running)
		  port = 2222; 
# dropbear uses key format different from openssh; can be generated by using:
# $ nix-shell -p dropbear --command "dropbearkey -t ecdsa -f /tmp/initrd-ssh-key"
                  # hostECDSAKey = /run/keys/initrd-ssh-key;
# public ssh key used for login
		  authorizedKeys = [ "ssh-rsa AAAA..." ];
	  };
# this will automatically load the zfs password prompt on login
# and kill the other prompt so boot can continue
	  postCommands = ''
		  echo "zfs load-key -a; killall zfs" >> /root/.profile
		  ''; 
  };

  # Select internationalisation properties.
  # i18n = {
  #   consoleFont = "Lat2-Terminus16";
  #   consoleKeyMap = "us";
  #   defaultLocale = "en_US.UTF-8";
  # };

  # Set your time zone.
  time.timeZone = "Europe/Brussels";

  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [
    lm_sensors
    cpufrequtils
    glibc
    cachix
  ];

  nixpkgs.config = {
    allowUnfree = true;
  };

  hardware.opengl = {
    driSupport32Bit = true;
    extraPackages32 = with pkgs.driversi686Linux; [
      mesa
    ];
  };
  hardware.pulseaudio.support32Bit = true;

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  # programs.mtr.enable = true;
  # programs.gnupg.agent = { enable = true; enableSSHSupport = true; };

  # List services that you want to enable:

  # Enable sound.
  sound.enable = true;

  # This value determines the NixOS release with which your system is to be
  # compatible, in order to avoid breaking some software such as database
  # servers. You should change this only after NixOS release notes say you
  # should.
  system.stateVersion = "20.03"; # Did you read the comment?

}

