# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/secure/nixos";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "rpool/secure/nixos/nix";
      fsType = "zfs";
    };
    
  fileSystems."/etc/nixos" =
    { device = "rpool/secure/nixos/configuration";
      fsType = "zfs";
    };

  fileSystems."/tmp" =
    { # device = "rpool/root/tmp";
      fsType = "tmpfs";
    };

  fileSystems."/home" =
    { device = "rpool/secure/home";
      fsType = "zfs";
    };

  fileSystems."/usr/local/steam" =
    { device = "rpool/secure/steam";
      fsType = "zfs";
    };

  fileSystems."/usr/local/vms" =
    { device = "rpool/secure/vms";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A0A3-486C";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 12;
}
